const { chromium } = require("/opt/node-tools/node_modules/playwright"); const fs = require("fs");
const R = "/home/user/zombocalypse/"; const sc = fs.readFileSync(R + "script.js", "utf8");
const part = sc.slice(sc.indexOf("// ---------- 49.48 คาสิโนเถื่อน"), sc.indexOf("function hubOpen(tab) {"));
(async () => {
  const br = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--no-sandbox"] }); const errs = [];
  const ctx = await br.newContext({ viewport: { width: 360, height: 780 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
  const pg = await ctx.newPage(); pg.on("pageerror", (e) => errs.push(String(e)));
  await pg.route("**/*", (r) => { const u = r.request().url(); if (u.includes("script.js")) return r.fulfill({ body: "" }); if (u.startsWith("file://")) return r.continue(); return r.abort(); });
  await pg.goto("file://" + R + "index.html");
  const out = await pg.evaluate(async (part) => {
    document.getElementById("screen-game").classList.add("active"); document.querySelectorAll(".screen").forEach((x) => { if (x.id !== "screen-game") x.classList.remove("active"); });
    const $ = (i) => document.getElementById(i), out = {}, calls = [];
    const mk = (t, c, x) => { const e = document.createElement(t); if (c) e.className = c; if (x !== undefined) e.textContent = x; return e; };
    const btn = (l, f, c = "btn primary mini") => { const b = mk("button", c, l); b.type = "button"; b.addEventListener("click", f); return b; };
    const state = { inv: { gold_watch: { id: "gold_watch", qty: 2 }, scrap: { id: "scrap", qty: 30 } } };
    const ITEMS = { gold_watch: { name: "นาฬิกาทอง", icon: "⌚" }, scrap: { name: "เศษวัสดุ", icon: "🔩" }, bandage: { name: "ผ้าพันแผล", icon: "🩹" } };
    let D = { ok: true, inZone: true, chips: 300, debt: null, lockLeft: 0, capLeft: 2000, lossToday: 0, cap: 2000, hpToday: 0, hpMax: 60, noLoan: 0, min: 5, max: 500, loanMax: 500, fee: 0.1, hpRate: 3, games: { bj: null, hl: null, vp: null }, note: [], warn: "x", rates: { gold_watch: 120, scrap: 2 }, shop: [{ id: "bandage", price: 9, day: 10, left: 10 }, { id: "deco_slotm", price: 2500, day: 1, left: 1 }], slotRtp: 95.1 };
    const casinoCall = async (d) => { calls.push(d); if (d.a === "slots") return { ...D, game: "slots", reels: ["🍒", "🍒", "🍋"], mult: 1.2, bet: d.bet, ret: 12, net: 2 }; if (d.a === "hilo" && d.act === "start") { D = { ...D, games: { ...D.games, hl: { bet: 10, card: "7♠", rank: 7, mult: 1.9 } } }; return { ...D, game: "hilo", started: true }; } if (d.a === "hilo") { D = { ...D, games: { ...D.games, hl: null } }; return { ...D, game: "hilo", card1: "7♠", card2: "K♥", win: true, tie: false, mult: 1.9, bet: 10, ret: 19, net: 9 }; } if (d.a === "poker" && d.act === "deal") { D = { ...D, games: { ...D.games, vp: { bet: 10, hand: ["A♠", "K♥", "10♦", "3♣", "3♠"], stage: "hold" } } }; return { ...D, game: "poker", started: true }; } if (d.a === "poker") { D = { ...D, games: { ...D.games, vp: null } }; return { ...D, game: "poker", hand: ["3♣", "3♠", "3♦", "K♥", "9♠"], kind: "trips", kindTh: "สามใบ", bet: 10, ret: 30, net: 20 }; } if (d.a === "roulette") return { ...D, game: "roulette", n: 17, red: false, bet: 10, ret: 0, net: -10 }; if (d.a === "sicbo") return { ...D, game: "sicbo", dice: [1, 2, 6], sum: 9, bet: 5, ret: 0, net: -5 }; if (d.a === "baccarat") return { ...D, game: "baccarat", P: ["5♠", "4♥"], B: ["K♦", "9♣"], p: 9, b: 9, win: "tie", side: d.side, bet: 10, ret: 90, net: 80 }; if (d.a === "blackjack") return { ...D, game: "blackjack", done: true, you: ["10♠", "9♥"], yv: 19, dealer: ["10♦", "8♣"], dv: 18, bet: 10, ret: 20, net: 10 }; if (d.a === "loan") { D = { ...D, chips: D.chips + d.n, debt: { a: Math.ceil(d.n * 1.25), due: Date.now() + 48 * 3600000, p: d.n } }; return D; } return D; };
    window.confirm = () => true;
    const toasts = []; const toast = (m) => toasts.push(m); const serverNow = () => Date.now(); const fnErr = (e) => String(e.message || e); const errMsg = fnErr;
    const zd = mk("div"); zd.id = "zone-desc"; document.body.prepend(zd);
    const api = new Function("state", "mk", "btn", "$", "casinoCall", "fnErr", "errMsg", "toast", "serverNow", "ITEMS", part + ";\nreturn { casinoBar, casinoOpen, casinoRender };")(state, mk, btn, $, casinoCall, fnErr, errMsg, toast, serverNow, ITEMS);
    api.casinoBar("casino"); out.bar = $("casino-bar").innerText; api.casinoBar("safe"); out.barGone = !$("casino-bar"); api.casinoBar("casino");
    $("casino-bar").querySelector("button").click(); await new Promise((r) => setTimeout(r, 150));
    const body = () => $("casino-body"), txt = () => body().innerText.replace(/\n/g, " | "), tabBtns = () => [...body().querySelectorAll(".casino-tabs button")], wait = () => new Promise((r) => setTimeout(r, 120));
    out.warnStrip = !!document.querySelector(".casino-warn-strip") && document.querySelector(".casino-warn-strip").innerText.includes("ไม่เคยทำให้ใครรวย");
    out.slots0 = txt().slice(0, 200);
    const clickT = async (t) => { const b = [...body().querySelectorAll("button")].find((x) => x.textContent.includes(t)); if (!b) { out["miss_" + t] = true; return; } b.click(); await wait(); };
    await clickT("หมุน"); out.slotsRes = txt().slice(-120);
    await clickT("รูเล็ต"); await clickT("แดง"); await clickT("แดง"); await clickT("＋เลขตรง"); out.rlTxt = txt().slice(-200); await clickT("หมุน ("); out.rlRes = txt().slice(-100); out.rlCall = JSON.stringify(calls.filter((c) => c.a === "roulette").pop());
    await clickT("ไฮโล"); [...body().querySelectorAll(".casino-grid button")][0].click(); await wait(); await clickT("ทอย"); out.sicCall = JSON.stringify(calls.filter((c) => c.a === "sicbo").pop()); out.sicRes = txt().slice(-100);
    await clickT("บาคาร่า"); await clickT("เสมอ"); await clickT("แจกไพ่"); out.bacCall = JSON.stringify(calls.filter((c) => c.a === "baccarat").pop()); out.bacRes = txt().slice(-130);
    await clickT("สูง-ต่ำ"); await clickT("เริ่ม"); out.hl1 = txt().slice(-120); await clickT("สูงกว่า"); out.hl2 = txt().slice(-100);
    await clickT("แบล็กแจ็ก"); await clickT("เริ่ม"); out.bj = txt().slice(-120);
    await clickT("โป๊กเกอร์"); await clickT("แจกไพ่"); const cards = [...body().querySelectorAll(".casino-card")]; out.cards = cards.length; cards[2].click(); await wait(); cards[2].click; await clickT("จั่ว"); out.vpCall = JSON.stringify(calls.filter((c) => c.a === "poker").pop()); out.vpRes = txt().slice(-100);
    await clickT("แลกชิป"); out.ex = txt().slice(0, 300); await clickT("ขาย 1"); out.sell = JSON.stringify(calls.filter((c) => c.a === "sell").pop()); await clickT("กู้ 100"); out.loan = txt().slice(0, 260);
    await clickT("ร้านแลก"); out.shop = txt().slice(-200); await clickT("อื่นๆ"); out.more = txt().slice(-220);
    out.hscroll = document.documentElement.scrollWidth > innerWidth; out.boxW = Math.round($("casino-modal").querySelector(".modal-box").getBoundingClientRect().width); out.toasts = toasts;
    state.csD.inZone = false; api.casinoRender(); out.outZone = txt().includes("ต้องอยู่ที่คาสิโนเถื่อน");
    return out;
  }, part);
  await pg.screenshot({ path: "shots/casino.png" });
  console.log(JSON.stringify(out, null, 1)); console.log("errors:", errs); await br.close();
})();
