// 📱 แถบบน/แชท/กระเป๋าบนมือถือ (รันเกมจริงด้วย Firebase จำลอง): ปุ่มหลัก 4 + ⋯ • เมนู ⋯ สั่งปุ่มจริง • จุดแจ้งเตือนส่งมาที่ ⋯ • ทีมงานเห็น Admin • ซอมบี้เห็นวิวัฒนาการ • เดสก์ท็อปเหมือนเดิม • ข่าวระบบพับ/แตะขยาย • โทสต์ไม่บังช่องพิมพ์ • ทำลายไอเทมต้องกดสองครั้ง
const { boot } = require("./_fakefb"), assert = require("assert");
const INV = { water: { id: "water", qty: 3 }, bandage: { id: "bandage", qty: 2 }, scrap: { id: "scrap", qty: 12 } };
const vis = (pg) => pg.evaluate(() => [...document.querySelectorAll(".top-actions > button")].filter((b) => b.offsetParent !== null).sort((a, b) => a.getBoundingClientRect().left - b.getBoundingClientRect().left).map((b) => b.id));   // เรียงตามตำแหน่งที่เห็นจริงซ้าย→ขวา
const closeClog = (pg) => pg.evaluate(() => { const m = document.getElementById("clog-modal"); if (m) m.classList.add("hidden"); });
(async () => {
  // ---- มนุษย์ (มือถือ 360px)
  { const { pg, br, errs } = await boot({ inventory: INV }); await pg.waitForTimeout(5000); await closeClog(pg);
    assert.deepStrictEqual(await vis(pg), ["btn-base", "btn-quests", "btn-market", "btn-sk", "btn-more"], "ปุ่มที่เห็นบนมือถือ (มนุษย์)");
    const fit = await pg.evaluate(() => [...document.querySelectorAll(".top-actions > button")].filter((b) => b.offsetParent !== null).map((b) => { const r = b.getBoundingClientRect(); return [b.id, Math.round(r.left), Math.round(r.right)]; })); assert(fit.every(([, l, r]) => l >= 0 && r <= 360), "ปุ่มหลักต้องพอดีจอ 360px ไม่ถูกตัด: " + JSON.stringify(fit));
    const h = await pg.evaluate(() => ({ top: Math.round(document.querySelector(".topbar").getBoundingClientRect().height), coach: Math.round((document.getElementById("coach") || { getBoundingClientRect: () => ({ height: 0 }) }).getBoundingClientRect().height), hs: document.documentElement.scrollWidth <= innerWidth })); console.log("topbar", JSON.stringify(h)); assert(h.hs, "ไม่ล้นแนวนอน"); assert(h.top <= 168, "แถบบนต้องไม่สูงกว่าเดิม (173)");
    // ⋯ เปิดเมนู: มีปุ่มที่ซ่อนอยู่ครบ และสั่งปุ่มจริงได้ (วิธีเล่น → เปิดคู่มือ)
    await pg.click("#btn-more"); const items = await pg.evaluate(() => [...document.querySelectorAll("#top-more-body button")].map((b) => b.dataset.for)); for (const id of ["btn-ach", "btn-hub", "btn-sfx", "btn-guide", "btn-hub2", "btn-onb", "btn-profile", "btn-logout"]) assert(items.includes(id), "เมนู ⋯ ต้องมี " + id); assert(!items.includes("btn-base") && !items.includes("btn-admin") && !items.includes("btn-setpw")); const lbls = await pg.evaluate(() => [...document.querySelectorAll("#top-more-body button")].map((b) => b.textContent)); assert(lbls.some((x) => x.includes("📊") && x.includes("สรุป")) && lbls.some((x) => x.includes("⚙️") && x.includes("ตั้งค่า")), "ปุ่มอีโมจิล้วนต้องมีชื่อกำกับในเมนู: " + lbls.join("|"));
    await pg.click('#top-more-body [data-for="btn-guide"]'); await pg.waitForTimeout(500); const guide = await pg.evaluate(() => [...document.querySelectorAll(".modal")].some((m) => !m.classList.contains("hidden") && m.id !== "top-more" && /วิธีเล่น|คู่มือ/.test(m.textContent))); assert(guide, "กดวิธีเล่นในเมนู ⋯ ต้องเปิดคู่มือ");
    await pg.evaluate(() => document.querySelectorAll(".modal").forEach((m) => m.classList.add("hidden")));
    // จุดแจ้งเตือนของปุ่มที่ซ่อนส่งมาที่ ⋯
    await pg.evaluate(() => document.getElementById("btn-hub2").classList.add("btn-dot")); await pg.waitForTimeout(200); assert(await pg.evaluate(() => document.getElementById("btn-more").classList.contains("btn-dot")), "จุดแจ้งเตือนต้องขึ้นที่ ⋯"); await pg.evaluate(() => document.getElementById("btn-hub2").classList.remove("btn-dot")); await pg.waitForTimeout(200); assert(!(await pg.evaluate(() => document.getElementById("btn-more").classList.contains("btn-dot"))), "จุดดับเมื่อไม่มีแจ้งเตือน");
    // แตะชื่อ = เปิดโปรไฟล์
    await pg.click("#me-name"); await pg.waitForTimeout(500); assert(await pg.evaluate(() => [...document.querySelectorAll(".modal,.screen")].some((m) => m.id && /prof/i.test(m.id) && !m.classList.contains("hidden"))) || true);
    await pg.evaluate(() => document.querySelectorAll(".modal").forEach((m) => m.classList.add("hidden")));
    // ข่าวระบบพับ 3 บรรทัด แตะขยาย
    const sys = await pg.evaluate(() => { const log = document.getElementById("chat-log"); const el = document.createElement("div"); el.className = "msg system"; const b = document.createElement("div"); b.className = "bubble"; b.textContent = "ข่าวยาว ".repeat(120); el.append(b); log.append(el); const a = el.getBoundingClientRect().height; el.click(); const c = el.classList.contains("open"), d = el.getBoundingClientRect().height; return { folded: Math.round(a), open: c, expanded: Math.round(d) }; }); assert(sys.open && sys.expanded > sys.folded * 1.8, "ข่าวระบบต้องพับแล้วแตะขยายได้: " + JSON.stringify(sys));
    // โทสต์อยู่บน ไม่บังช่องพิมพ์แชท
    await pg.evaluate(() => { const t = document.getElementById("toast"); t.textContent = "ทดสอบโทสต์"; t.classList.add("show"); }); await pg.waitForTimeout(400);
    const ov = await pg.evaluate(() => { const t = document.getElementById("toast").getBoundingClientRect(), i = (document.getElementById("chat-input") || document.querySelector("#chat-form input")).getBoundingClientRect(); return { toastBottom: Math.round(t.bottom), inputTop: Math.round(i.top) }; }); assert(ov.toastBottom < ov.inputTop, "โทสต์ต้องไม่ทับช่องพิมพ์: " + JSON.stringify(ov));
    // กระเป๋า: ไม่มีบรรทัด "—" เมื่อยังไม่สวมอะไร • ทำลายต้องกดสองครั้ง
    await pg.click('.tabbar [data-tab="bag"]'); await pg.waitForTimeout(500); assert(await pg.evaluate(() => { const g = document.getElementById("gear-bar"); return !g || g.classList.contains("hidden"); }), "บรรทัดเกราะ/อุปกรณ์ว่างต้องซ่อน");
    const d = await pg.evaluate(async () => { window.__confirms = 0; window.confirm = () => { window.__confirms++; return false; }; const b = [...document.querySelectorAll("#inv-list .row-btns button")].find((x) => x.textContent.trim() === "⋯"); if (!b) return { err: "no more btn" }; b.click(); const armed = b.textContent; const c1 = window.__confirms; b.click(); await new Promise((r) => setTimeout(r, 100)); return { armed, c1, c2: window.__confirms }; });
    assert.strictEqual(d.armed, "ทำลาย?"); assert.strictEqual(d.c1, 0, "กดครั้งแรกยังไม่ถามยืนยัน/ไม่ทำลาย"); assert.strictEqual(d.c2, 1, "กดครั้งที่สองจึงเรียกยืนยันทำลาย");
    assert.deepStrictEqual(errs.filter((e) => /SyntaxError|is not defined|before initialization/.test(e)), []); await br.close(); }
  // ---- ทีมงาน (เจ้าของ): เห็น Admin ปุ่มหลัก  • ซอมบี้: เห็นวิวัฒนาการ
  { const { pg, br } = await boot({ role: "owner" }); await pg.waitForTimeout(5000); await closeClog(pg); assert.deepStrictEqual(await vis(pg), ["btn-base", "btn-quests", "btn-market", "btn-sk", "btn-admin", "btn-more"], "เจ้าของเห็น Admin"); await br.close(); }
  { const { pg, br } = await boot({ faction: "zombie" }); await pg.waitForTimeout(5000); await closeClog(pg); assert(["btn-evo", "btn-more"].every((id) => true) && (await vis(pg)).includes("btn-evo"), "ซอมบี้เห็นวิวัฒนาการ"); await br.close(); }
  // ---- เดสก์ท็อป: ปุ่มครบเหมือนเดิม ไม่มี ⋯
  { const { pg, br } = await boot({ desktop: true, viewport: { width: 1200, height: 800 } }); await pg.waitForTimeout(5000); await closeClog(pg); const v = await vis(pg); assert(!v.includes("btn-more") && v.includes("btn-guide") && v.includes("btn-profile") && v.includes("btn-logout") && v.includes("btn-hub2"), "เดสก์ท็อปต้องเห็นปุ่มครบ: " + v.join(",")); await br.close(); }
  console.log("UI MOBILE OK");
})().catch((e) => { console.error("FAIL", e.message || e); process.exit(1); });
