process.env.FIREBASE_DATABASE_EMULATOR_HOST = "127.0.0.1:9000";
const fs = require("fs");
const admin = require("/home/user/zombocalypse/functions/node_modules/firebase-admin");
const { initializeTestEnvironment } = require("@firebase/rules-unit-testing");
const NS = "demo-zombo"; if (!admin.apps.length) admin.initializeApp({ projectId: NS, databaseURL: `http://127.0.0.1:9000?ns=${NS}` });
const adb = admin.database(); const SV = admin.database.ServerValue.TIMESTAMP;
const R = { old: fs.readFileSync("rules_old.json", "utf8"), nw: fs.readFileSync("rules_new.json", "utf8") };
const U = "u1", T = "u2";
const user = (o = {}) => ({ username: "tester", faction: "human", role: "player", banned: false, zone: "safe", stamina: 100, staminaTs: Date.now(), hp: 100, food: 100, water: 100, foodTs: Date.now(), waterTs: Date.now(), lastTravel: Date.now() - 600000, ...o });
(async () => {
  const env = await initializeTestEnvironment({ projectId: NS, database: { host: "127.0.0.1", port: 9000, rules: R.old } });
  let cur = "old";
  const setRules = async (k) => { if (cur === k) return; const r = await fetch(`http://127.0.0.1:9000/.settings/rules.json?ns=${NS}`, { method: "PUT", headers: { Authorization: "Bearer owner" }, body: R[k] }); if (!r.ok) throw new Error("rules put " + r.status); cur = k; };
  const run = async (k, seed, up, who = U) => { await setRules(k); await adb.ref().set(JSON.parse(JSON.stringify(seed))); const db = env.authenticatedContext(who, { firebase: { sign_in_provider: "password" } }).database(); try { await db.ref().update(up); return true; } catch { return false; } };
  let bad = 0, n = 0;
  const expect = async (name, seed, up, eo, en, who) => { n++; const a = await run("old", seed, up, who), b = await run("nw", seed, up, who); const ok = a === eo && b === en; if (!ok) bad++; console.log(ok ? "ok  " : "FAIL", name, "old", a, "new", b, `(expected ${eo}/${en})`); };
  const travel = (z) => ({ [`users/${U}/zone`]: z, [`users/${U}/lastTravel`]: SV, [`users/${U}/stamina`]: 50, [`users/${U}/staminaTs`]: SV });
  await expect("travel safe→casino", { users: { [U]: user({ stamina: 100 }) } }, travel("casino"), false, true);
  await expect("travel safe→ruins (unchanged)", { users: { [U]: user() } }, travel("ruins"), true, true);
  await expect("travel safe→bogus zone", { users: { [U]: user() } }, travel("narnia"), false, false);
  await expect("travel casino→safe", { users: { [U]: user({ zone: "casino" }) } }, travel("safe"), true, true);
  const atk = (zone) => ({ [`attacks/${T}/${U}`]: { from: U, fromName: "tester", roll: 3, zone, ts: SV, dmg: 10 }, [`users/${U}/lastAttack`]: SV });
  await expect("attack in ruins (control)", { users: { [U]: user({ zone: "ruins" }), [T]: user({ zone: "ruins", username: "t2" }) } }, atk("ruins"), true, true);
  await expect("attack in casino (must be blocked)", { users: { [U]: user({ zone: "casino" }), [T]: user({ zone: "casino", username: "t2" }) } }, atk("casino"), true, false);
  await expect("attack in safe (wall intact: blocked)", { users: { [U]: user({ zone: "safe" }), [T]: user({ zone: "safe", username: "t2" }) } }, atk("safe"), false, false);
  const boss = (z) => ({ [`bossFights/${U}`]: { boss: z, hp: 100, max: 100, zone: z, ts: SV }, [`users/${U}/lastBoss`]: SV });
  await expect("boss in ruins (control)", { users: { [U]: user({ zone: "ruins" }) } }, boss("ruins"), true, true);
  await expect("boss in casino (blocked)", { users: { [U]: user({ zone: "casino" }) } }, boss("casino"), false, false);
  const chat = (z) => ({ [`chats/${z}/m1`]: { uid: U, name: "tester", faction: "human", text: "hi", type: "chat", ts: SV }, [`users/${U}/lastChat`]: SV });
  await expect("chat in ruins (control)", { users: { [U]: user({ zone: "ruins" }) } }, chat("ruins"), true, true);
  await expect("chat in casino", { users: { [U]: user({ zone: "casino" }) } }, chat("casino"), true, true);
  console.log(`${n} cases, ${bad} unexpected`); process.exit(bad ? 1 : 0);
})().catch((e) => { console.error("FAIL", e); process.exit(1); });
