process.env.FIREBASE_DATABASE_EMULATOR_HOST = "127.0.0.1:9000";
const admin = require("/home/user/zombocalypse/functions/node_modules/firebase-admin");
const { initializeApp } = require("firebase/app");
const { getAuth, connectAuthEmulator, createUserWithEmailAndPassword, signInWithEmailAndPassword } = require("firebase/auth");
const { getFunctions, connectFunctionsEmulator, httpsCallable } = require("firebase/functions");
const NS = "zompocalypse-137a6-default-rtdb";
admin.initializeApp({ projectId: "demo-zombo", databaseURL: `http://127.0.0.1:9000?ns=${NS}` });
const db = admin.database();
const mkClient = async (name) => {
  const app = initializeApp({ projectId: "demo-zombo", apiKey: "fake", authDomain: "x" }, name);
  const auth = getAuth(app); connectAuthEmulator(auth, "http://127.0.0.1:9099", { disableWarnings: true });
  const fns = getFunctions(app, "asia-southeast1"); connectFunctionsEmulator(fns, "127.0.0.1", 5001);
  const cred = await createUserWithEmailAndPassword(auth, `${name}${Date.now()}@b.co`, "secret12");
  const call = httpsCallable(fns, "marketAct");
  return { uid: cred.user.uid, call: (d) => call(d).then((r) => r.data) };
};
const user = (n, o = {}) => ({ username: n, faction: "human", role: "player", banned: false, zone: "safe", hp: 100, ...o });
const T = async (label, p) => { try { const r = await p; console.log(label, "->", JSON.stringify(r)); return r; } catch (e) { console.log(label, "-> ERR", e.code, e.message); return null; } };
(async () => {
  const A = await mkClient("a"), B = await mkClient("b"), C = await mkClient("c");
  await db.ref().set({ users: { [A.uid]: user("alice"), [B.uid]: user("bob"), [C.uid]: user("carl") }, inventory: { [A.uid]: { bandage: { id: "bandage", qty: 5 }, knife: { id: "knife", qty: 1, dur: 12, maxDur: 30 } , w1: { id: "knife", qty: 1, dur: 9, maxDur: 30 } }, [B.uid]: { scrap: { id: "scrap", qty: 10 }, chem: { id: "chem", qty: 4 } }, [C.uid]: { scrap: { id: "scrap", qty: 10 } } } });
  const inv = async (u) => (await db.ref(`inventory/${u}`).get()).val();
  console.log("--- sell");
  const s1 = await T("A sell 3 bandage for 4 scrap", A.call({ a: "sell", g: "bandage", gq: 3, wants: [{ id: "scrap", qty: 4 }] }));
  await T("A sell weapon w1 for 2 chem + 1 scrap", A.call({ a: "sell", g: "w:w1", wants: [{ id: "chem", qty: 2 }, { id: "scrap", qty: 1 }] }));
  await T("A sell dup wants", A.call({ a: "sell", g: "bandage", gq: 1, wants: [{ id: "scrap", qty: 1 }, { id: "scrap", qty: 1 }] }));
  console.log("A inv", JSON.stringify(await inv(A.uid)), "market", JSON.stringify((await db.ref("market/human").get()).val()));
  console.log("--- buy race (B and C both buy listing 1)");
  const lid = `${A.uid}_1`;
  const rs = await Promise.allSettled([B.call({ a: "buy", lid }), C.call({ a: "buy", lid })]);
  console.log(rs.map((r) => r.status === "fulfilled" ? "ok" : r.reason.code + ":" + r.reason.message).join(" | "));
  console.log("B inv", JSON.stringify(await inv(B.uid)), "\nC inv", JSON.stringify(await inv(C.uid)), "\npayouts A", JSON.stringify((await db.ref(`marketPayouts/${A.uid}`).get()).val()));
  console.log("--- buy weapon listing, claim, cancel");
  await T("B buy weapon (needs chem 2 + scrap 1)", B.call({ a: "buy", lid: `${A.uid}_2` }));
  console.log("B inv", JSON.stringify(await inv(B.uid)));
  const pays = (await db.ref(`marketPayouts/${A.uid}`).get()).val() || {};
  for (const pid of Object.keys(pays)) await T("A claim " + pid, A.call({ a: "claim", pid }));
  console.log("A inv", JSON.stringify(await inv(A.uid)));
  await T("A sell again then cancel", A.call({ a: "sell", g: "bandage", gq: 2, wants: [{ id: "chem", qty: 1 }] }));
  await T("A cancel", A.call({ a: "cancel", lid: `${A.uid}_1` }));
  await T("A cancel nonexistent", A.call({ a: "cancel", lid: `${A.uid}_3` }));
  console.log("A inv", JSON.stringify(await inv(A.uid)));
  console.log("--- black market");
  await T("rotate", B.call({ a: "bmRotate" })); await T("rotate again", B.call({ a: "bmRotate" }));
  const bm = (await db.ref("bm/human").get()).val(); console.log("bm", JSON.stringify(bm).slice(0, 220));
  await db.ref(`inventory/${B.uid}/scrap`).set({ id: "scrap", qty: 60 });
  await T("B bmBuy o1", B.call({ a: "bmBuy", k: "o1" })); await T("B bmBuy o1 again", B.call({ a: "bmBuy", k: "o1" }));
  const rs2 = await Promise.allSettled(["o5", "o5", "o5"].map((k, i) => [B, C][i % 2] && (i < 2 ? [B, C][i] : B).call({ a: "bmBuy", k })));
  console.log("bm race", rs2.map((r) => r.status === "fulfilled" ? "ok" : r.reason.message).join(" | "));
  console.log("--- gift");
  await db.ref(`inventory/${C.uid}/water`).set({ id: "water", qty: 3 });
  await T("C gift water -> B", C.call({ a: "gift", to: B.uid, id: "water" }));
  await T("C gift again too fast", C.call({ a: "gift", to: B.uid, id: "water" }));
  await T("C gift bad id", C.call({ a: "gift", to: B.uid, id: "scrap" }));
  console.log("payouts B", JSON.stringify((await db.ref(`marketPayouts/${B.uid}`).get()).val()), "C inv", JSON.stringify(await inv(C.uid)));
  console.log("locks left:", JSON.stringify((await db.ref("locks").get()).val()));
  process.exit(0);
})().catch((e) => { console.error("E2E FAIL", e); process.exit(1); });
